### ISSUE TITLE
Allow installing ripsecrets via homebrew

### ISSUE THREAD

**Issue by sirwart** [sirwart/ripsecrets#28]
I'm not sure exactly what's entailed by this, but I don't think it would be too difficult

**Comment by seththeriault** [comment]
Here is the cookbook:

https://docs.brew.sh/Formula-Cookbook

**Comment by colindean** [comment]
This will probably qualify for Homebrew core inclusion by the end of May. I'll take it on by then, you could assign this to me.

**Comment by sirwart** [comment]
@colindean thanks Colin! I saw that authors aren't supposed to submit their own project so I'd appreciate it :-)

**Comment by colindean** [comment]
`ripsecrets` is now in Homebrew: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ripsecrets.rb

**Comment by colindean** [comment]
https://formulae.brew.sh/formula/ripsecrets

**Comment by sirwart** [comment]
Thanks @colindean, I really appreciate it!
