### ISSUE TITLE
The name "secrets" complicates discovery

### ISSUE THREAD

**Issue by colindean** [sirwart/ripsecrets#3]
While `secrets` is basically "get secrets" and expect none to be returned, the name is, well, not very S.E.O. friendly. @sirwart, are you open to considering some other names while this tool is still in its infancy?

**Comment by grawlinson** [comment]
Agreed, considering that is a GNOME tool that has the [same name](https://gitlab.gnome.org/World/secrets) (yet different functionality).

**Comment by sirwart** [comment]
I named it in honor of the venerable `strings` utility, which I guess is also not very SEO friendly. I wanted it to feel more like a unix utility and less like a product with a clever name. I'm open to new names but don't have any ideas at the moment

**Comment by yigitsever** [comment]
The name also complicates packaging the application for [archlinux user repository](https://aur.archlinux.org/)

Since you mentioned that you are open to new names, I'd like to suggest `ripsecrets`, 'rip-' is already associated with searching thanks to `ripgrep` and this utility searches for secrets :)

**Comment by ComedyTomedy** [comment]
Perhaps something on the detect-secrets model of {scan,detect,grep,find}-{secrets,keys,leaks}... E.g. detect-leaks.

keyleaks sounds good while being "unixy".

scankey is funny cos it sounds like skanky :p

Personally I wouldn't worry too much about SEO - people will just search "secrets GitHub" or whatever, but having the right name in repos is really useful.

**Comment by sirwart** [comment]
@yigitsever I kinda like ripsecrets. I don't think it should be abbreviated it like `rg`, but since it's not a tool you're invoking manually terribly often that's OK. I'll keep thinking about that.

**Comment by magnetophon** [comment]
Another comment from [HN](https://news.ycombinator.com/item?id=31087508):
```
You might want to pick a different name since it collides with my already-published crate.
https://crates.io/crates/secrets
```

**Comment by sirwart** [comment]
I just updated the name of the tool to `ripsecrets`. Thanks for the feedback everyone!
