### ISSUE TITLE
Finalize pre-commit configuration

### ISSUE THREAD

**Issue by sirwart** [sirwart/ripsecrets#30]
According to this PR: https://github.com/sirwart/ripsecrets/pull/2:

> Once this is merged, someone (me?) could put a PR on https://github.com/pre-commit/pre-commit.com/blob/main/all-repos.yaml that adds https://github.com/sirwart/secrets to it.

Someone needs to add https://github.com/sirwart/ripsecrets to the pre-commit repository.

**Comment by lafrenierejm** [comment]
> Someone needs to add https://github.com/sirwart/ripsecrets to the pre-commit repository.

IMO you, @sirwart, would be the best suited to raise the PR against pre-commit give you're the original and primary author of ripsecrets. Would you prefer that someone else raise the PR instead?

**Comment by sirwart** [comment]
@lafrenierejm I had just created it as a TODO item to see if anyone would tackle it before I got a chance. However I just opened a PR against pre-commit so I'll end up doing it.

**Comment by lafrenierejm** [comment]
For future reference, the PR is https://github.com/pre-commit/pre-commit.com/pull/663

**Comment by sirwart** [comment]
It's now been merged
