### ISSUE TITLE
Running cargo install downloads sentry submodule

### ISSUE THREAD

**Issue by sirwart** [sirwart/ripsecrets#48]
When trying to install ripsecrets via cargo I noticed that it now tries to download the entire sentry module because it's listed as a submodule, which takes a long time because it's a large repo. Either the configuration needs to change or removed as a submodule.

**Comment by lafrenierejm** [comment]
Oof. I didn't realize that was part of Cargo's behavior. https://github.com/rust-lang/cargo/issues/4247 seems like a relevant discussion. https://github.com/dtolnay/syn/pull/183, linked from the Cargo issue, looks like a potential way forward.

**Comment by sirwart** [comment]
Yea, it seems like the only way forward is to not use submodules and just clone explicitly when needed, right?

**Comment by lafrenierejm** [comment]
That's what it sounds like based on https://github.com/rust-lang/cargo/issues/4247. I'll take a stab at it…

**Comment by sirwart** [comment]
Sounds good, thanks!
