### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by colindean** [sirwart/ripsecrets#77]
Splitting off from https://github.com/sirwart/ripsecrets/issues/66#issuecomment-1591071018 and https://github.com/sirwart/ripsecrets/issues/66#issuecomment-1722413032, it'd be great if this was uploading to crates.io on release.

https://doc.rust-lang.org/cargo/reference/publishing.html

https://users.rust-lang.org/t/does-anyone-use-github-actions-to-run-cargo-publish/92374

**Comment by lafrenierejm** [comment]
Following https://github.com/sirwart/ripsecrets/pull/85, the release Actions workflow now publishes the crate to [crates.io](https://crates.io/). The crate should become available the next time a new version is tagged.

**Comment by lafrenierejm** [comment]
@sirwart Following up on this and <https://github.com/sirwart/ripsecrets/issues/66#issuecomment-1962737567> again. Have you given any more thought to triggering the release workflow?

**Comment by lafrenierejm** [comment]
@sirwart Gentle nudge to publish a crate. :)
