### ISSUE TITLE
support quay robot token pattern

### ISSUE THREAD

**Issue by jmelahman** [sirwart/ripsecrets#79]
The only official reference to syntax I could find was this image  
![image](https://github.com/sirwart/ripsecrets/assets/49570001/2d7d48e3-9c3b-4454-82e4-a2d2a12fbaf2)
from https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/use_red_hat_quay/use-quay-manage-repo

Pretty sure it's just `"[A-Z0-9]{64}"` though.

**Comment by jmelahman** [comment]
This particular pattern might be overly susceptible to false positives, but maybe sufficient to only check within word-boundaries, `"\b[A-Z0-9]{64}\b"`

**Comment by jmelahman** [comment]
Seems awfully slow too :sweat: . Seeing almost 100x runtime overhead :/

**Comment by sirwart** [comment]
Hi @jmelahman, for patterns without a predefined prefix, `ripsecrets` relies on the random secret detector (found here: https://github.com/sirwart/ripsecrets/blob/main/src/matcher/mod.rs#L9). This will catch these tokens as long as they're on the same line as something that indicates it's a secret (such as "token", "secret", or "password").
