### ISSUE TITLE
not that fast.. show benchmarks

### ISSUE THREAD

**Issue by jaredxx1** [sirwart/ripsecrets#84]
it's very slow compared to rg (with all the extras removed) - I only checked for 3 piped rgxs

**Comment by lafrenierejm** [comment]
Any chance you could provide a sample repository and the regular expressions you benchmarked?

**Comment by sirwart** [comment]
You can see how I tested the performance here: https://github.com/sirwart/ripsecrets?tab=readme-ov-file#performance. Even though the tool is built using rg, it's still running quite a large regex on the code being scanned. It should be compared to other secret scanning tools.
